import '../styles/globals.css'
import type { Metadata } from 'next'
import { Crimson_Text } from 'next/font/google'

const crimson = Crimson_Text({ subsets: ['latin'], weight: '400' })
// const crimsonItalic = Crimson_Text({ subsets: ['latin'], weight: '400', style: 'italic' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={crimson.className}>{children}</body>
    </html>
  )
}
